<?php
/**
 * Initialize the custom theme options.
 */
add_action( 'init', 'custom_theme_options' );

/**
 * Build the custom settings & update OptionTree.
 */
function custom_theme_options() {
  
	// OptionTree is not loaded yet, or this is not an admin request.
	if ( ! function_exists( 'ot_settings_id' ) || ! is_admin() ) {
		return false;
	}

	// Get a copy of the saved settings array.
	$saved_settings = get_option( ot_settings_id(), array() );

	// Custom settings array that will eventually be passes to the OptionTree Settings API Class.
	$custom_settings = array(
		'contextual_help' => array(
			'sidebar' => '',
		),
		'sections'        => array(
			array(
				'id'    => 'header',
				'title' => esc_html__( 'Header', 'vulture' ),
			),
			array(
				'id'    => 'home_page',
				'title' => esc_html__( 'Home Page', 'vulture' ),
			),
			array(
				'id'    => 'footer',
				'title' => esc_html__( 'Footer', 'vulture' ),
			),
			array(
				'id'    => 'social_media',
				'title' => esc_html__( 'Social Media', 'vulture' ),
			),
			array(
				'id'    => '404',
				'title' => esc_html__( '404 page', 'vulture' ),
			),
			array(
				'id'    => 'single',
				'title' => esc_html__( 'Single page', 'vulture' ),
			),
			array(
				'id'    => 'custom_style',
				'title' => esc_html__( 'Custom Style', 'vulture' ),
			),
		),
		'settings'        => array(
			array(
				'id'           => 'logo',
				'label'        => esc_html__( 'Header Logo', 'vulture' ),
				'desc'         => esc_html__( 'Please upload a logo image in 125*35 px.', 'vulture' ),
				'std'          => '',
				'type'         => 'upload',
				'section'      => 'header',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'light_header_logo',
				'label'        => esc_html__( 'Light header logo', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'upload',
				'section'      => 'header',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'showsearch',
				'label'        => esc_html__( 'Show search form', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'header',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'showabout',
				'label'        => esc_html__( 'Show About me Section', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'bigimg',
				'label'        => esc_html__( 'Home page image', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'upload',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'big_title_text',
				'label'        => esc_html__( 'Big title text', 'vulture' ),
				'desc'         => esc_html__( 'Write big title of home page. Example: Hi, I&#039;m a Web Developer', 'vulture' ),
				'std'          => '',
				'type'         => 'text',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'description',
				'label'        => esc_html__( 'Description', 'vulture' ),
				'desc'         => esc_html__( 'Please write description for show in home page', 'vulture' ),
				'std'          => '',
				'type'         => 'textarea',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'textbtn',
				'label'        => esc_html__( 'Button text', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'linkbtn',
				'label'        => esc_html__( 'Button Link', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'showposts',
				'label'        => esc_html__( 'Show posts section', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'titleposts_section',
				'label'        => esc_html__( 'Articles section title', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'custom_link_text',
				'label'        => esc_html__( 'Custom link text', 'vulture' ),
				'desc'         => esc_html__( 'Add custom text for Articles section link', 'vulture' ),
				'std'          => '',
				'type'         => 'text',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'custom_url_link',
				'label'        => esc_html__( 'Custom URL link', 'vulture' ),
				'desc'         => esc_html__( 'Add custom link URL for Articles section link', 'vulture' ),
				'std'          => '',
				'type'         => 'text',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'custom_html',
				'label'        => esc_html__( 'Custom HTML', 'vulture' ),
				'desc'         => esc_html__( 'You can add html codes for home page. this code show under the sections.', 'vulture' ),
				'std'          => '',
				'type'         => 'textarea',
				'section'      => 'home_page',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'copyright',
				'label'        => esc_html__( 'Copyright text', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'footer',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'showsocial',
				'label'        => esc_html__( 'Show social media icons', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'footer',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'instagram',
				'label'        => esc_html__( 'Intagram URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'facebook',
				'label'        => esc_html__( 'Facebook URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'linkedin',
				'label'        => esc_html__( 'Linkedin URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'twitter',
				'label'        => esc_html__( 'Twitter URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'github',
				'label'        => esc_html__( 'Github URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'dribbble',
				'label'        => esc_html__( 'Dribbble URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'youtube',
				'label'        => esc_html__( 'Youtube URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'pinterest',
				'label'        => esc_html__( 'Pinterest URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'rss',
				'label'        => esc_html__( 'RSS URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'wordpress',
				'label'        => esc_html__( 'Wordpress URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => 'social_media',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'upload_custom_image',
				'label'        => esc_html__( 'Upload custom image', 'vulture' ),
				'desc'         => esc_html__( 'upload a image for show in 404 page.', 'vulture' ),
				'std'          => '',
				'type'         => 'upload',
				'section'      => '404',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'error_content_page',
				'label'        => esc_html__( 'Content', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'textarea',
				'section'      => '404',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'button_text_404',
				'label'        => esc_html__( 'Button text', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => '404',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'button_url_404',
				'label'        => esc_html__( 'Button link URL', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'text',
				'section'      => '404',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'show_breadcrumb',
				'label'        => esc_html__( 'Show breadcrumb', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'single',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'show_post_date',
				'label'        => esc_html__( 'Show post date', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'single',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'show_share_buttons',
				'label'        => esc_html__( 'Show share buttons', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'single',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'show_author_box',
				'label'        => esc_html__( 'Show author box', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'single',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'show_related_posts',
				'label'        => esc_html__( 'Show Related Posts', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'single',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'main_color',
				'label'        => esc_html__( 'Main Color', 'vulture' ),
				'desc'         => esc_html__( 'Main color is the color of your branding. this the color is some texts and sections in website.', 'vulture' ),
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'darkmode',
				'label'        => esc_html__( 'Dark mode', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'selection_color',
				'label'        => esc_html__( 'Selection color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'selection_background',
				'label'        => esc_html__( 'Selection background color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'link_color',
				'label'        => esc_html__( 'Post link color ', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'link_hover_color',
				'label'        => esc_html__( 'Post link hover color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'buttons_color',
				'label'        => esc_html__( 'Buttons color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'buttons_background_color',
				'label'        => esc_html__( 'Buttons background color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'buttons_hover_color',
				'label'        => esc_html__( 'Buttons hover color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'buttons_hover_background_color',
				'label'        => esc_html__( 'Buttons hover background color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'sidebar_link_color',
				'label'        => esc_html__( 'Sidebar Link color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'sidebar_link_hover_color',
				'label'        => esc_html__( 'Sidebar link hover color', 'vulture' ),
				'desc'         => '',
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'custom_style',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
		)
	);

	// Allow settings to be filtered before saving.
	$custom_settings = apply_filters( ot_settings_id() . '_args', $custom_settings );

	// Settings are not the same update the DB.
	if ( $saved_settings !== $custom_settings ) {
		update_option( ot_settings_id(), $custom_settings ); 
	}

	// Lets OptionTree know the UI Builder is being overridden.
	global $ot_has_custom_theme_options;
	$ot_has_custom_theme_options = true;
}
